name: Run clustering notebook

on: [push]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install jupyter nbconvert

    - name: Show my files
      run: ls -R

    - name: Execute my notebook
      run: jupyter nbconvert --to notebook --execute food_nutrition_analysis.ipynb
